### ISSUE TITLE
config.js contains project-specific names...

### ISSUE THREAD

**Issue by ged-lendinvest** [QuatroCode/simplr-gulp#11]
Example below:
"quatrodev:*": "wwwroot/libs/quatrodev/*",
"quatrodev-insider:*": "wwwroot/libs/quatrodev-insider/*"

**Comment by GiedriusGrabauskas** [comment]
It's custom registries (private npm) in JSPM. [Read more...](https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#creating-new-registries)
I removed that in [v1.10](https://github.com/QuatroCode/simplr-gulp/tree/v1.10)
